### ISSUE TITLE
Issue 1: Users can discover the amount of calories that they can eat 

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can discover the amount of calories that they can eat 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be greeted with a form page upon visiting the website. They can toggle between metric system or imperial system. After submitting their results, they see their daily calorie intake and their  goal.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![desktop 1-1](https://user-images.githubusercontent.com/47346471/154580779-58a85300-c1da-4e44-8ce7-f3d7b071541b.png)
![desktop 1-2](https://user-images.githubusercontent.com/47346471/154580781-9724dc84-4bd3-4a97-a0f4-5468a4a29b53.png)
![desktop 1-3](https://user-images.githubusercontent.com/47346471/154581266-78c083d4-1841-4973-95ae-c57f25fcda49.png)
![desktop 1-4](https://user-images.githubusercontent.com/47346471/154581017-4f6d1cef-ca63-435e-94c5-0e38264b9c82.png)
a8.png)

![1-1](https://user-images.githubusercontent.com/47346471/154579367-f8b92d5b-b3e0-43c9-933a-d535f97fc757.png)
![1-2](https://user-images.githubusercontent.com/47346471/154579369-ef37f974-5b5e-4539-a43b-db9ef5a16395.png)
![1-3](https://user-images.githubusercontent.com/47346471/154581207-5e4f2a5e-d835-4cbe-86df-02a30c48361d.png)
![1-4](https://user-images.githubusercontent.com/47346471/154579376-108f05ee-485c-49f6-96c2-f1dc237dae8b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to the variant that I created through DbDesigner.
- [x] Update `data.sql` to include an admin user for Priority 1 Development....

### ☁️ Server

- [x] Update `server/index.js` to include a PUT method, for Priority 1, the admin will be getting updated, but to the end-user, it seems that they are receiving a new profile.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a Navbar Component
  - [x] Create an anchor tag that says Calculator.
- [x] Create a Home Page.
- [x] Create a Header Component.
- [x] Create a Calorie form Component:
  - [x] Include the Icon Ox and a H2 tag as the header 
  - [x]  Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
  - [x] Make all inputs of the entry form required
  - [x] Have a radio button up top indicating whether Metric or Imperial system is being used
  - [x] Implement a submit button
  - [x] When the user hits submit, calculate their TDEE with inputs,
    - [x] If metric was selected, convert inches to Centimeters, and pounds to Kilograms
  - [x] Display users results after the submit button is pressed, replace their dailyCalories in the database. 

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
