### ISSUE TITLE
Issue 6: User can register to Accountability-Buddy

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users are able to Register to Accountability-Buddy

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User selects Register from the Navbar, the User can enter in a username and password and hit register.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="555" alt="Feature 6-1" src="https://user-images.githubusercontent.com/47346471/155813058-92bb6e70-ac95-4f1a-89e2-1ec3fc9c1450.png">
<img width="561" alt="Feature 6-2" src="https://user-images.githubusercontent.com/47346471/155813063-44959a57-b8bf-4160-a20e-465f60262a4d.png">
<img width="444" alt="Feature 6" src="https://user-images.githubusercontent.com/47346471/155813066-72736329-4c28-489e-9de8-9359f6d74fa6.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to implement a new post method which inserts a new user. Implement the argon2 package for the hashed password. Do not send back response back showing the hashedpassword.... 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update Navbar component to include a new Register anchor tab
- [x] Create a Registration component:
  - [x] Have a form that contains two inputs, text and password.
  - [x] Have form controls to prevent mischief and added security for the user
  - [x] When Submitted, perform a fetch post request
    - [x] When loading, return the loading component 
    - [x] if successful, notify the user that their account is created. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
