### ISSUE TITLE
Issue 7: User can Sign-in

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can sign in to their account on Accountability-Buddy.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![sign-in desktop](https://user-images.githubusercontent.com/47346471/155858268-637272a7-e573-445e-99f6-9a0f4c8aa336.png)
![sign-in mobile](https://user-images.githubusercontent.com/47346471/155858269-bce572e4-5f2b-45db-85ff-d73d4679877f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to correlate userID with each meal or exercise that getrs added. (foreign key)...

### ☁️ Server

- [x] Update `server/index.js` to include a get method to verify that the user's username and password match, if it matches hand the user a token. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the auth-form Component
  - [x] where if the user wants to sign-in, display the form as a sign-in page
  - [x] When the user hits submit, perform a get method, authenticate the user, and give them the authorization to use the app.
  - [x] Have a sign-in as a guest button, so the user can quickly get access to the app for exploration reasons.
- [x] Update the Navbar Component
  - [x] If the user is not signed in, hide every anchor tag outside of Register
  - [x] If the user is signed in, Display every anchor tag except Register
- [x] Update the meals, exercises, edit-meal, edit-exercise, codex and calculator pages
  - [x] Implement a guard, If the user isn't signed in, then redirect the user to the sign-in page.
- [x] Update the App Component, if in componentdidMount, retrieve user's token and give them authorization.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
