### ISSUE TITLE
Issue 8: User can Sign out

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/final-project#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can sign out of Accountability Buddy.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If Signed in, User can hit the sign out button, from there they are signed out of their accountability buddy application.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 8-1 Desktop](https://user-images.githubusercontent.com/47346471/156903593-fe933392-d505-4563-b3ab-5e4eaaf3b333.png)
![Feature 8-1](https://user-images.githubusercontent.com/47346471/156903594-be4f1ee2-3e15-41e2-996f-4a6171054cf8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update Navbar component to include a signout button
- [x] Update App.jsx to include a handle signout function
  - [ ] Inside handlesignout, remove the user's token from local storage 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
