### ISSUE TITLE
Issue 2: Users can create meals, that tracks its total calorie count

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add meals that they created.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will access the form page by click on the navbar anchor tab, from there, they will fill out the required components.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Desktop 2-1](https://user-images.githubusercontent.com/47346471/154128958-1a96bcc4-e15b-48cb-ad98-54f93cbce369.png)
<img width="634" alt="d 2-2" src="https://user-images.githubusercontent.com/47346471/154770903-8f5b00e7-212a-492d-9b50-5c4ecadbd1cf.png">

![Mobile 2-1](https://user-images.githubusercontent.com/47346471/154128971-2bce48cf-21eb-41ad-b863-bd41df1d95d2.png)
<img width="253" alt="m 2-2" src="https://user-images.githubusercontent.com/47346471/154770855-8506c93b-0290-4462-8f75-fed98c3e37ff.png">
![2-3b](https://user-images.githubusercontent.com/47346471/154128973-8b916094-38df-4b25-b833-bf3b7eae03d5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a new POST method for adding meals.
  - [x] include any necessary conditions to prevent junk data from entering. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the Navbar Component to include a new Meal anchor tag.
- [x] Create a new Meal Page.
- [x] Create an Add Item Form component.
  - [x]  Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
  - [x] Include the Ox and the correct heading.
  - [x] Make all inputs of the entry form required
  - [x] Implement a submit button, for the form in order to trigger handleSubmit.
  - [x] In the handleSubmit, incorporate a POST method that adds the meal item to the meals table under userId: 1
- [x] Update Stats component
  - [x] To distinguish whether the data is from the Item form or the calculator form. 
  - [x] Display the information that the user inputted. 
  - [x] Include an anchor tag that can quickly take the user back to the item home page.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
