### ISSUE TITLE
Issue 3: Users can add exercises, that tracks the calories burned

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add exercises, that tracks the calories burned

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users enters the form page from the anchor tag, they fill out the required fields and are greeted with a message indicating that their meal has been added.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-02-15 at 11 20 51 AM](https://user-images.githubusercontent.com/47346471/154133754-7f9d15fc-b01c-4ab3-91fa-fcb551f9bcb4.png)

![3-2](https://user-images.githubusercontent.com/47346471/154776299-47249404-3e69-41a6-a54b-d761d03c5620.png)

![Screen Shot 2022-02-18 at 3 58 53 PM](https://user-images.githubusercontent.com/47346471/154776278-38e4ea33-4597-45e5-a2d9-a5d8cfab0935.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a new post method for add new exercises.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the Navbar component to include a new Exercise anchor tag.
- [x] Create a new Exercise Page
- [x] Update the Add Item Form Component
  - [x] Have a new condition to determine what "Item" is being updated, have form labels update along with place holders.
  - [x] Include the Ox and the correct Corresponding header
  - [x] In the Handle Submit, modify the post method's first argument (directory string), have a variable at the end to decide whether it's a meal or exercise.
  - [x] Send the data to the stats component as a prop
- [x] Update the Stats page
  - [x] Include a new conditional indicating that exercises was being passed and render the relevant information.

### 🧑‍⚕️ Clean Up

- [x] Refactor all code modified, the next feature is going to need it. 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
