### ISSUE TITLE
Issue 4: Users can drag and drop their meals or Exercises to quickly gauge their calorie count for the day

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can drag and drop their meals or Exercises to quickly gauge their calorie count for the day
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user enters the page from the navbar, they are greeted with three columns. They can adjust the items in each column by dragging and dropping with a handle.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-02-15 at 11 26 26 AM](https://user-images.githubusercontent.com/47346471/154134847-0cf75d32-fcce-4c10-b395-1313e0b5b617.png)
![Screen Shot 2022-02-15 at 11 26 47 AM](https://user-images.githubusercontent.com/47346471/154134853-4aecb56a-b0a4-4f89-8372-d4dfdae34800.png)
![Screen Shot 2022-02-15 at 11 27 06 AM](https://user-images.githubusercontent.com/47346471/154134876-0b4093cb-a608-4c35-b559-ddae0e176bbe.png)
![Screen Shot 2022-02-15 at 11 27 21 AM](https://user-images.githubusercontent.com/47346471/154134878-cbf71e1e-fad0-4651-b7aa-2bcb2bc2eb16.png)
![Screen Shot 2022-02-15 at 11 27 40 AM](https://user-images.githubusercontent.com/47346471/154134881-721eb429-6998-4d38-8ec6-d5a75e35d3a6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include to get methods for the meals and calories. One method to get user Calories
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a Journal page
- [x] Update the Navbar page to include the Journal Page
- [x] Create a class component that gets the User's daily calorie, meals, and exercises.
- [x] Create a Column component
  - [x] Create three elements and style them. Have real-time effects when an item gets grabbed,
  - [x] import Droppable
- [x] Create a Task component
  - [x] Create the container element and the Handle Method
  - [x] import the Draggable context 
- [x] Create a drag component
  - [x] import DragDropContext
  - [x] have the onDragStart, onDragUpdate, and onDragEnd
  - [x] render DragDropContext, have container and column nested component as a child
 - [x] Update the Handle to indicate whether the item is an exercise or meal.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
