### ISSUE TITLE
Issue 5: Users can edit or delete their exercises or meals.

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can edit or delete their meals and exercises.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can click on the Edit tag on the Navbar, a drop will occur which list Edit Meal or Edit Exercise. They are greeted with their meals or exercises, from their they can edit or delete their meal. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![5-1d](https://user-images.githubusercontent.com/47346471/155434224-bdd4f0ad-434e-45f1-86d2-1c45740768cf.png)
![5-2d](https://user-images.githubusercontent.com/47346471/155434226-d33107eb-3588-47c7-b78e-b585eedfc927.png)
![5-3](https://user-images.githubusercontent.com/47346471/155434227-7d4615f3-a500-4ada-90ef-ce05feb7e862.png)
![5-4](https://user-images.githubusercontent.com/47346471/155434228-b067e3bf-5b76-403b-87ac-b5c7dd99e794.png)
![5-5](https://user-images.githubusercontent.com/47346471/155434229-59921041-24db-4d45-8560-0a8db9130324.png)
![5-6](https://user-images.githubusercontent.com/47346471/155434230-b858de8d-f503-4801-8576-51f31e73c9a6.png)
![5-7](https://user-images.githubusercontent.com/47346471/155434232-d6ae2b32-801c-4ec6-90bf-079e4267a658.png)

![5-1m](https://user-images.githubusercontent.com/47346471/155434244-981cbbd6-157f-4623-8a4c-6f043d55313d.png)
![5-2m](https://user-images.githubusercontent.com/47346471/155434252-43d4cff8-ded8-40a3-a556-76249ae0b291.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to:
  - [x] Include a Put and Delete Method for meals
  - [x] Include a Put and Delete Method for exercises
  - [x] Edit the get method for meals and exercises, and send back the correct data in a convenient format.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update NavBar component to include a DropDown Edit Anchor Tag with Exercises or Meals being the selection ...
- [x] Create a new edit-meal and edit-exercise page.
- [x] Create a new edit-item Component
  - [x] Retrieve all items for the selected item (meal or exercises) through a fetch request
  - [x] Display all items, which now have a edit icon or an x icon
  - [x] if the User clicks an edit icon display a form
    - [x] Once the user hits the submit button, perform a put fetch request at the item's Id, and return the new modified item using the stats component.
    - [x] If the user hits a delete button, a modal pops up, if the user confirms it, perform a delete request at the **item's id**  and return the stats component indicating that the item has been deleted.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
